server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Example-for-graduate-work
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: "db.changelog/db.changelog.yml"

upload:
  dir: "src/main/resources/images"